[package]
name = "sdl2-test"
version = "0.1.0"
authors = ["tommi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32"
libc = "0.2.5"
rand = "0.7.0"